trigger:
- master

pool:
  vmImage: windows-latest

variables:
  projectPath: '**/WebApp9May.csproj' # Simplified for flexibility
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project'
  inputs:
    azureSubscription: 'azure-Demo-Conn'
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: FileTransform@2
  displayName: 'JSON Variable Substitution'
  inputs:
    folderPath: '$(Build.ArtifactStagingDirectory)/**/*.zip' # Target the zip specifically
    enableJsonTransform: true
    jsonTargetFiles: '**/appsettings.json'

- task: PublishBuildArtifacts@1
  displayName: 'Upload Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# - task: AzureWebApp@1
#   displayName: 'Deploy to Azure Web App'
#   inputs:
#     azureSubscription: 'azure-Demo-Conn'
#     appType: 'webApp'
#     appName: 'Webapp101'
#     package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
#     deploymentMethod: 'auto'